import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box />
      </main>

      <footer className={styles.footer}>
        <Bold text="block"/> 
        {"by"}
        <Bold text="block" />
      </footer>
    </div>
  )
}

function Bold({text}) {
  return (
    <>
      <>&nbsp;</>
      <span style={{fontWeight: "bold"}}>
        {text}
      </span>
      <>&nbsp;</>
    </>
  )
}

function Box() {
  return (
    <div style={{
      width: "100px",
      height: "100px",
      background: "black"
    }}/>
  )
}
